@EventsService.Api_HostAddress = http://localhost:5000

GET {{EventsService.Api_HostAddress}}/events
Accept: application/json

###

POST {{EventsService.Api_HostAddress}}/events
Content-Type: application/json

{
  "title": "Conference",
  "description": "Annual tech conference",
  "startAt": "2026-09-01T10:00:00Z",
  "endAt": "2026-09-01T18:00:00Z"
}

###

PUT {{EventsService.Api_HostAddress}}/events/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "title": "Conference (updated)",
  "description": "Annual tech conference",
  "startAt": "2026-09-01T10:00:00Z",
  "endAt": "2026-09-01T19:00:00Z"
}

###

DELETE {{EventsService.Api_HostAddress}}/events/00000000-0000-0000-0000-000000000000

###
